require 'sad_panda/version'
require 'sad_panda/status_message'
require 'lingua/stemmer'
require './lib/sad_panda/emotions/emotion_bank'
require './lib/sad_panda/emotions/term_polarities'
require './lib/sad_panda/emotions/stopwords'